POST https://7wp1z6igic.execute-api.us-east-1.amazonaws.com/dev/animals
Content-Type: application/json

{
  "name": "Bunny",
  "age": "2",
  "family": "Cat"
}

###
GET https://7wp1z6igic.execute-api.us-east-1.amazonaws.com/dev/animals

###
DELETE https://7wp1z6igic.execute-api.us-east-1.amazonaws.com/dev/animals/Bunny